ALTER TABLE public.meal_logs
  ADD COLUMN IF NOT EXISTS protein integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS carbs integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS sugars integer NOT NULL DEFAULT 0;