
INSERT INTO public.recipes (name, meal_type, calories, protein, carbs, fat, prep_time, cook_time, difficulty_level, category, ingredients, instructions, tags) VALUES
-- 2 more breakfasts (to reach 10)
('Spinach Mushroom Omelette', 'breakfast', 380, 28, 8, 26, '5 minutes', '10 minutes', 'easy', 'unspecified',
 '["3 eggs (210 cal)","1 cup spinach (7 cal)","1/2 cup mushrooms (10 cal)","1 oz feta cheese (75 cal)","1 tsp olive oil (40 cal)","Salt and pepper (0 cal)"]'::jsonb,
 '["Whisk eggs in a bowl with salt and pepper","Heat olive oil in a non-stick skillet over medium heat","Sauté mushrooms until golden, about 3 minutes","Add spinach and cook until wilted","Pour eggs over vegetables","Cook until edges set, then sprinkle feta on one side","Fold omelette in half and slide onto a plate"]'::jsonb,
 ARRAY[]::text[]),
('Banana Almond Smoothie Bowl', 'breakfast', 420, 18, 58, 14, '10 minutes', '0 minutes', 'easy', 'unspecified',
 '["1 frozen banana (105 cal)","1 cup almond milk (40 cal)","2 tbsp almond butter (190 cal)","1 scoop protein powder (120 cal)","1 tbsp chia seeds (60 cal)","1/4 cup granola (90 cal)","Fresh berries for topping (30 cal)"]'::jsonb,
 '["Blend frozen banana, almond milk, almond butter, and protein powder until thick","Pour into a chilled bowl","Top with chia seeds, granola, and fresh berries","Serve immediately"]'::jsonb,
 ARRAY[]::text[]),

-- 8 more lunches (to reach 10)
('Mediterranean Chickpea Salad', 'lunch', 520, 22, 55, 24, '15 minutes', '0 minutes', 'easy', 'unspecified',
 '["1.5 cups chickpeas (220 cal)","1 cucumber, diced (45 cal)","1 cup cherry tomatoes (27 cal)","1/4 red onion (16 cal)","2 oz feta cheese (150 cal)","10 kalamata olives (50 cal)","2 tbsp olive oil (240 cal)","1 tbsp lemon juice (4 cal)","Fresh oregano (0 cal)"]'::jsonb,
 '["Rinse and drain chickpeas","Dice cucumber, halve tomatoes, and thinly slice red onion","Combine chickpeas, vegetables, olives, and feta in a large bowl","Whisk olive oil, lemon juice, and oregano","Toss salad with dressing","Season with salt and pepper and serve"]'::jsonb,
 ARRAY[]::text[]),
('Chicken Caesar Wrap', 'lunch', 580, 42, 48, 24, '10 minutes', '15 minutes', 'easy', 'unspecified',
 '["6 oz grilled chicken breast (280 cal)","1 large whole wheat tortilla (170 cal)","2 cups romaine lettuce (16 cal)","2 tbsp Caesar dressing (160 cal)","2 tbsp parmesan cheese (40 cal)","1 tbsp lemon juice (4 cal)"]'::jsonb,
 '["Season chicken with salt and pepper","Grill chicken 6-7 minutes per side until cooked through","Let chicken rest, then slice","Toss romaine with Caesar dressing and parmesan","Lay tortilla flat and add lettuce mixture and chicken","Squeeze lemon over filling","Roll tightly and slice in half"]'::jsonb,
 ARRAY[]::text[]),
('Quinoa Black Bean Bowl', 'lunch', 610, 24, 88, 18, '10 minutes', '20 minutes', 'easy', 'unspecified',
 '["1 cup cooked quinoa (220 cal)","1 cup black beans (220 cal)","1/2 avocado (120 cal)","1/2 cup corn (66 cal)","1/4 cup salsa (20 cal)","2 tbsp Greek yogurt (30 cal)","Fresh cilantro (0 cal)","1 lime (10 cal)"]'::jsonb,
 '["Cook quinoa according to package directions","Warm black beans in a small saucepan","Slice avocado","Layer quinoa, beans, and corn in a bowl","Top with avocado, salsa, and Greek yogurt","Garnish with cilantro and lime juice"]'::jsonb,
 ARRAY[]::text[]),
('Thai Peanut Noodle Salad', 'lunch', 640, 26, 72, 28, '15 minutes', '10 minutes', 'medium', 'unspecified',
 '["4 oz rice noodles (200 cal)","4 oz cooked chicken (180 cal)","1 cup shredded carrots (50 cal)","1 cup red cabbage (28 cal)","2 tbsp peanut butter (190 cal)","1 tbsp soy sauce (10 cal)","1 tsp sriracha (5 cal)","2 tbsp crushed peanuts (105 cal)"]'::jsonb,
 '["Cook rice noodles per package, rinse with cold water","Whisk peanut butter, soy sauce, sriracha, and 2 tbsp warm water","Toss noodles, chicken, carrots, and cabbage with sauce","Top with crushed peanuts and serve chilled"]'::jsonb,
 ARRAY[]::text[]),
('Tuna Avocado Lettuce Wraps', 'lunch', 420, 32, 14, 26, '10 minutes', '0 minutes', 'easy', 'unspecified',
 '["2 cans tuna in water (220 cal)","1 avocado (240 cal)","2 tbsp Greek yogurt (30 cal)","1 tbsp lemon juice (4 cal)","1 stalk celery, diced (6 cal)","8 large butter lettuce leaves (10 cal)","Salt and pepper (0 cal)"]'::jsonb,
 '["Drain tuna and place in a bowl","Mash avocado and mix with tuna","Stir in Greek yogurt, lemon juice, and celery","Season with salt and pepper","Spoon mixture into lettuce leaves and serve"]'::jsonb,
 ARRAY[]::text[]),
('Caprese Pasta Salad', 'lunch', 560, 20, 70, 22, '10 minutes', '12 minutes', 'easy', 'unspecified',
 '["2 cups cooked whole wheat pasta (350 cal)","6 oz fresh mozzarella balls (180 cal)","1 cup cherry tomatoes (27 cal)","1/4 cup fresh basil (1 cal)","2 tbsp balsamic glaze (60 cal)","1 tbsp olive oil (120 cal)"]'::jsonb,
 '["Cook pasta until al dente, drain and cool","Halve cherry tomatoes and mozzarella balls","Tear basil leaves","Combine pasta, tomatoes, mozzarella, and basil","Drizzle with olive oil and balsamic glaze","Toss gently and serve"]'::jsonb,
 ARRAY[]::text[]),
('Buffalo Chicken Bowl', 'lunch', 540, 44, 38, 22, '10 minutes', '15 minutes', 'easy', 'unspecified',
 '["6 oz chicken breast (280 cal)","2 tbsp buffalo sauce (10 cal)","1 cup brown rice (215 cal)","1 cup shredded lettuce (10 cal)","1/4 cup blue cheese crumbles (100 cal)","1/4 cup shredded carrots (12 cal)","2 tbsp ranch dressing (140 cal)"]'::jsonb,
 '["Cook brown rice according to package directions","Season chicken and grill or pan-sear 6 minutes per side","Slice chicken and toss with buffalo sauce","Build bowl with rice, lettuce, and carrots","Top with chicken, blue cheese, and ranch drizzle"]'::jsonb,
 ARRAY[]::text[]),
('Veggie Hummus Power Wrap', 'lunch', 480, 18, 62, 18, '10 minutes', '0 minutes', 'easy', 'unspecified',
 '["1 large spinach tortilla (170 cal)","1/4 cup hummus (100 cal)","1/2 cucumber sliced (22 cal)","1/2 red bell pepper (15 cal)","1/4 cup shredded carrots (12 cal)","1 cup baby spinach (7 cal)","1/4 avocado (60 cal)","2 tbsp feta cheese (50 cal)"]'::jsonb,
 '["Spread hummus evenly over the tortilla","Layer spinach, cucumber, bell pepper, carrots, and avocado","Sprinkle feta cheese over vegetables","Roll wrap tightly, tucking in the sides","Slice diagonally and serve"]'::jsonb,
 ARRAY[]::text[]),

-- 7 more dinners (to reach 10)
('Beef Stir Fry with Broccoli', 'dinner', 620, 42, 48, 26, '15 minutes', '15 minutes', 'medium', 'unspecified',
 '["8 oz lean beef sirloin (320 cal)","2 cups broccoli florets (60 cal)","1 red bell pepper (30 cal)","1 cup cooked brown rice (215 cal)","2 tbsp soy sauce (20 cal)","1 tbsp sesame oil (120 cal)","2 cloves garlic (8 cal)","1 tsp fresh ginger (2 cal)"]'::jsonb,
 '["Slice beef thinly against the grain","Heat sesame oil in a wok over high heat","Stir-fry beef for 2-3 minutes until browned, remove","Add garlic, ginger, broccoli, and bell pepper, stir-fry 4 minutes","Return beef and add soy sauce","Toss everything together for 1 minute","Serve over brown rice"]'::jsonb,
 ARRAY[]::text[]),
('Sheet Pan Lemon Herb Chicken', 'dinner', 580, 46, 40, 22, '10 minutes', '30 minutes', 'easy', 'unspecified',
 '["8 oz chicken thighs (380 cal)","2 cups baby potatoes (160 cal)","1 cup green beans (35 cal)","2 tbsp olive oil (240 cal)","1 lemon (12 cal)","2 tsp Italian herbs (0 cal)","3 cloves garlic (12 cal)"]'::jsonb,
 '["Preheat oven to 425°F","Halve baby potatoes and trim green beans","Toss everything with olive oil, garlic, herbs, and lemon zest","Arrange on a sheet pan with chicken in center","Roast for 25-30 minutes until chicken is cooked through","Squeeze fresh lemon juice before serving"]'::jsonb,
 ARRAY[]::text[]),
('Shrimp Garlic Pasta', 'dinner', 590, 32, 65, 20, '10 minutes', '15 minutes', 'easy', 'unspecified',
 '["8 oz shrimp, peeled (240 cal)","2 cups cooked linguine (350 cal)","4 cloves garlic (16 cal)","2 tbsp olive oil (240 cal)","1/4 cup white wine (50 cal)","2 tbsp parsley (5 cal)","1 tbsp lemon juice (4 cal)","Red pepper flakes (0 cal)"]'::jsonb,
 '["Cook linguine until al dente","Heat olive oil in a large skillet over medium heat","Sauté minced garlic for 30 seconds","Add shrimp and cook 2 minutes per side","Pour in wine and lemon juice, simmer 2 minutes","Toss with pasta, parsley, and red pepper flakes","Serve immediately"]'::jsonb,
 ARRAY[]::text[]),
('Turkey Meatballs with Zucchini Noodles', 'dinner', 510, 38, 28, 26, '15 minutes', '20 minutes', 'medium', 'unspecified',
 '["1 lb ground turkey (480 cal)","3 medium zucchini, spiralized (90 cal)","1 cup marinara sauce (80 cal)","1 egg (70 cal)","1/4 cup breadcrumbs (110 cal)","2 tbsp parmesan (40 cal)","2 cloves garlic (8 cal)","1 tbsp olive oil (120 cal)"]'::jsonb,
 '["Mix turkey, egg, breadcrumbs, parmesan, and garlic","Form into 1-inch meatballs","Heat olive oil and brown meatballs on all sides","Add marinara, cover, and simmer 12 minutes","Sauté zucchini noodles briefly until just tender","Serve meatballs and sauce over zoodles"]'::jsonb,
 ARRAY[]::text[]),
('Vegetarian Lentil Curry', 'dinner', 480, 22, 72, 12, '10 minutes', '30 minutes', 'easy', 'unspecified',
 '["1 cup red lentils (350 cal)","1 can light coconut milk (200 cal)","1 onion, diced (45 cal)","3 cloves garlic (12 cal)","1 tbsp curry powder (20 cal)","1 can diced tomatoes (70 cal)","2 cups spinach (14 cal)","1 tbsp olive oil (120 cal)"]'::jsonb,
 '["Heat olive oil in a pot and sauté onion until soft","Add garlic and curry powder, cook 1 minute","Stir in lentils, tomatoes, and coconut milk","Add 2 cups water, bring to boil","Reduce heat and simmer 20-25 minutes until lentils are tender","Stir in spinach until wilted","Serve hot, optionally over rice"]'::jsonb,
 ARRAY[]::text[]),
('Baked Cod with Roasted Vegetables', 'dinner', 460, 38, 32, 18, '10 minutes', '25 minutes', 'easy', 'unspecified',
 '["8 oz cod fillet (180 cal)","2 cups Brussels sprouts (80 cal)","1 cup butternut squash (80 cal)","2 tbsp olive oil (240 cal)","1 lemon (12 cal)","2 cloves garlic (8 cal)","Fresh thyme (0 cal)"]'::jsonb,
 '["Preheat oven to 400°F","Halve Brussels sprouts and cube squash","Toss vegetables with half the olive oil, salt, and pepper","Roast for 15 minutes","Place cod on sheet pan, drizzle with remaining oil, garlic, and thyme","Top with lemon slices and roast 10 more minutes until cod flakes easily"]'::jsonb,
 ARRAY[]::text[]),
('Pork Tenderloin with Apple Slaw', 'dinner', 560, 44, 38, 24, '15 minutes', '25 minutes', 'medium', 'unspecified',
 '["8 oz pork tenderloin (320 cal)","2 cups shredded cabbage (44 cal)","1 apple, julienned (95 cal)","2 tbsp Greek yogurt (30 cal)","1 tbsp apple cider vinegar (3 cal)","1 tbsp honey (60 cal)","1 tbsp olive oil (120 cal)","1 tsp paprika (6 cal)"]'::jsonb,
 '["Preheat oven to 400°F","Rub pork tenderloin with olive oil, paprika, salt, and pepper","Sear pork in a hot ovenproof skillet, 2 minutes per side","Transfer to oven and roast 15-18 minutes until 145°F internal","Whisk yogurt, vinegar, and honey","Toss cabbage and apple with dressing","Rest pork 5 minutes, slice, and serve with slaw"]'::jsonb,
 ARRAY[]::text[]);
